#!/usr/bin/env ruby
# frozen_string_literal: true

require "rspec/candy"

silent = ARGV.delete("--silent") || ARGV.delete("-s")
coverage_path = ARGV[0] || RSpec::Candy::Coverage::DEFAULT_COVERAGE_PATH
lib_filter = ARGV[1] || "lib/"

reporter = RSpec::Candy::Coverage.new(coverage_path: coverage_path, lib_filter: lib_filter)
exit(reporter.report(silent: silent) ? 0 : 1)
